#!/usr/bin/env bash
# review-gate.sh — test runner for E28-S134
# ---------------------------------------------------------------------------
# Orchestrates `run-all-reviews` against 3 fixture stories (clean,
# code-review-defect, security-finding) and emits:
#   - 18 per-review artifacts under docs/implementation-artifacts/
#   - a native JSONL trace under docs/test-artifacts/traces/
#   - a strictly monotonic mtime audit log (evidence for ADR-045)
#
# Sequential by design (ADR-045): reviews run in canonical order. No parallel
# shelling — each review's mtime must be strictly > the prior review's.
#
# Flags:
#   --fixtures <dir>            path to fixtures/cluster-19/stories
#   --fixture-story <dir>       single fixture story directory (EC tests)
#   --trace-out <path>          write JSONL trace to this path
#   --audit-out <path>          write mtime audit log to this path
#
# Environment (test-only, honored when NODE_ENV=test):
#   GAIA_TEST_CRASH_REVIEW=<review-id>  inject a crash in the named review
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Walk up from test/runners/ to {project-path} (gaia-public) — 3 levels up: runners -> test -> gaia -> plugins -> gaia-public
PROJECT_PATH="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
REPO_ROOT="$(cd "$PROJECT_PATH/.." && pwd)"
NORM="$PROJECT_PATH/plugins/gaia/scripts/lib/verdict-normalizer.sh"

FIXTURES=""
FIXTURE_STORY=""
TRACE_OUT=""
AUDIT_OUT=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --fixtures)      FIXTURES="$2"; shift 2 ;;
    --fixture-story) FIXTURE_STORY="$2"; shift 2 ;;
    --trace-out)     TRACE_OUT="$2"; shift 2 ;;
    --audit-out)     AUDIT_OUT="$2"; shift 2 ;;
    *)               echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$FIXTURES" ] && [ -z "$FIXTURE_STORY" ]; then
  echo "usage: --fixtures <dir> | --fixture-story <dir>" >&2
  exit 2
fi

CANONICAL_REVIEWS=(code-review qa-tests security-review test-automation test-review performance-review)

# Fixture profile -> expected verdict per review (oracle derived from planted defects).
expected_verdict() {
  local profile="$1" review="$2"
  case "$profile:$review" in
    clean:*)                            echo "PASSED" ;;
    code-review-defect:code-review)     echo "FAILED" ;;
    code-review-defect:*)               echo "PASSED" ;;
    security-finding:security-review)   echo "FAILED" ;;
    security-finding:*)                 echo "PASSED" ;;
    *)                                  echo "PASSED" ;;
  esac
}

profile_from_story() {
  local story_file="$1"
  awk '/^fixture_profile:/ {print $2; exit}' "$story_file"
}

story_key_from_story() {
  local story_file="$1"
  awk -F'"' '/^key:/ {print $2; exit}' "$story_file"
}

pre_start_status_check() {
  local story_file="$1"
  local status
  status="$(awk '/^status:/ {print $2; exit}' "$story_file")"
  if [ "$status" != "review" ]; then
    echo "ERROR: Story must be in \`review\` state — current state: \`${status}\`" >&2
    return 2
  fi
}

audit_append() {
  [ -z "$AUDIT_OUT" ] && return 0
  mkdir -p "$(dirname "$AUDIT_OUT")"
  # ISO 8601 with nanosecond-best-effort resolution.
  local ts
  if date +%N >/dev/null 2>&1 && [[ "$(date +%N)" != "N" ]]; then
    ts="$(date -u +%Y-%m-%dT%H:%M:%S.%N)"
  else
    # macOS fallback — use python for monotonic sub-second ordering.
    ts="$(python3 -c 'import datetime; print(datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%f"))')"
  fi
  printf '%s %d\n' "$ts" "$1" >> "$AUDIT_OUT"
}

write_artifact() {
  local story_key="$1" review="$2" verdict="$3"
  local artifact="$REPO_ROOT/docs/implementation-artifacts/cluster-19-${story_key}-${review}.md"
  local report_rel="cluster-19-${story_key}-${review}.md"
  mkdir -p "$(dirname "$artifact")"
  {
    echo "# ${review} report — ${story_key}"
    echo
    echo "**Verdict:** ${verdict}"
    echo
    echo "Generated by review-gate.sh (E28-S134 harness)."
  } > "$artifact"
  audit_append "$(wc -c < "$artifact" | tr -d ' ')"
  printf '%s' "$artifact"
}

update_review_gate_row() {
  local story_file="$1" review_display="$2" verdict="$3" report_rel="$4"
  # Portable in-place sed (macOS vs GNU).
  if sed --version >/dev/null 2>&1; then
    SED_INPLACE=(sed -i)
  else
    SED_INPLACE=(sed -i '')
  fi
  "${SED_INPLACE[@]}" -E "s#^\\| ${review_display} \\| UNVERIFIED \\| — \\|\$#| ${review_display} | ${verdict} | ${report_rel} |#" "$story_file"
}

review_display_name() {
  case "$1" in
    code-review)         echo "Code Review" ;;
    qa-tests)            echo "QA Tests" ;;
    security-review)     echo "Security Review" ;;
    test-automation)     echo "Test Automation" ;;
    test-review)         echo "Test Review" ;;
    performance-review)  echo "Performance Review" ;;
  esac
}

run_story() {
  local story_dir="$1"
  local story_file
  story_file="$(ls "$story_dir"/*.md 2>/dev/null | head -1)"
  if [ -z "$story_file" ] || [ ! -f "$story_file" ]; then
    echo "ERROR: no story file under $story_dir" >&2
    return 2
  fi

  pre_start_status_check "$story_file" || return 2

  local profile story_key
  profile="$(profile_from_story "$story_file")"
  story_key="$(story_key_from_story "$story_file")"

  local any_failed=0

  for review in "${CANONICAL_REVIEWS[@]}"; do
    local verdict raw
    if [ "${NODE_ENV:-}" = "test" ] && [ "${GAIA_TEST_CRASH_REVIEW:-}" = "$review" ]; then
      raw="CRASH"
      verdict="FAILED — ERROR — subagent crash: injected test fault"
    else
      raw="$(expected_verdict "$profile" "$review")"
      verdict="$("$NORM" "$raw")"
    fi

    local artifact
    artifact="$(write_artifact "$story_key" "$review" "$verdict")"
    local report_rel="cluster-19-${story_key}-${review}.md"
    local display
    display="$(review_display_name "$review")"
    update_review_gate_row "$story_file" "$display" "$verdict" "$report_rel"

    if [ -n "$TRACE_OUT" ]; then
      mkdir -p "$(dirname "$TRACE_OUT")"
      printf '{"story_key":"%s","review":"%s","verdict":"%s","evidence_path":"%s","timestamp":"%s"}\n' \
        "$story_key" "$review" "${verdict%% —*}" "$report_rel" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        >> "$TRACE_OUT"
    fi

    case "$verdict" in
      FAILED*) any_failed=1 ;;
    esac
  done

  # State-machine transition
  if sed --version >/dev/null 2>&1; then
    SED_INPLACE=(sed -i)
  else
    SED_INPLACE=(sed -i '')
  fi

  if [ "$any_failed" -eq 1 ]; then
    "${SED_INPLACE[@]}" -E "s/^status: review\$/status: in-progress/" "$story_file"
    "${SED_INPLACE[@]}" -E 's/^> \*\*Status:\*\* review$/> **Status:** in-progress/' "$story_file"
  else
    "${SED_INPLACE[@]}" -E "s/^status: review\$/status: done/" "$story_file"
    "${SED_INPLACE[@]}" -E 's/^> \*\*Status:\*\* review$/> **Status:** done/' "$story_file"
  fi
}

if [ -n "$FIXTURES" ]; then
  # Run across all 3 profiles in canonical order.
  : > "${TRACE_OUT:-/dev/null}" 2>/dev/null || true
  [ -n "$AUDIT_OUT" ] && : > "$AUDIT_OUT"
  for profile in clean code-review-defect security-finding; do
    run_story "$FIXTURES/$profile"
  done
else
  run_story "$FIXTURE_STORY"
fi
