#!/usr/bin/env bats
# test-automate-phase2.bats
#
# ATDD red-phase tests for E35-S3:
#   Phase 2 main-context execution with drift + plan_id verification
#
# Epic: E35 — Test Automate Fork-Context Fix
# Risk: HIGH
# ATDD document: docs/test-artifacts/atdd-E35-S3.md
# Generated: 2026-04-22 by Sable (Master Test Architect)
#
# All tests FAIL in the red phase because Phase 2 does not yet exist
# in gaia-public/plugins/gaia/skills/gaia-test-automate/SKILL.md.
#
# Test framework: bats-core (https://github.com/bats-core/bats-core)
# Run: bats gaia-public/plugins/gaia/tests/test-automate-phase2.bats
#
# AC coverage:
#   AC1  TC-TAF-7  FR-TAF-4  — triple-source verdict agree
#   AC2  TC-TAF-6  FR-TAF-4  — plan_id mismatch (concurrent race)
#   AC3  TC-TAF-9  FR-TAF-4  — frontmatter tamper
#   AC4  TC-TAF-4  FR-TAF-3  — source drift halt
#   AC5  TC-TAF-5  FR-TAF-3  — path outside allowlist
#   AC6  TC-TAF-7  FR-TAF-1  FR-TAF-3  — happy-path end-to-end
#   AC7  FR-TAF-1  — main-context Write/Edit allowed
#   AC8  FR-TAF-1  — plan phase=executed + story/sprint updates
#   AC9  TC-TAF-7  — V1 regression parity
#   AC-EC1  boundary  — empty analyzed_sources no-op
#   AC-EC2  boundary  — empty proposed_tests 0-case evidence
#   AC-EC3  error     — plan file missing
#   AC-EC4  data      — malformed YAML frontmatter
#   AC-EC5  security  — path traversal in test_file
#   AC-EC6  environment — test-environment.yaml missing
#   AC-EC7  concurrency — documented limitation (skipped)
#   AC-EC8  integration — bridge unavailable, graceful degrade
#   AC-EC9  integration — ledger empty/missing
#   AC-EC10 error     — target file already exists

load 'test_helper.bash'

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# PHASE2_ENTRYPOINT resolves relative to the tests/ directory one level up,
# then down into skills/gaia-test-automate/scripts/. Tests fail at run time
# (status 127) if the script does not exist — which is the expected red-phase
# failure mode.
PLUGIN_ROOT_DEFAULT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

# ---------------------------------------------------------------------------
# Shared setup / teardown
# ---------------------------------------------------------------------------

setup() {
  common_setup

  PLUGIN_ROOT="${PLUGIN_ROOT:-$PLUGIN_ROOT_DEFAULT}"
  PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "$BATS_TEST_FILENAME")/../../.." && pwd)}"

  PHASE2_ENTRYPOINT="$PLUGIN_ROOT/skills/gaia-test-automate/scripts/phase2-execute.sh"
  REVIEW_GATE="$PLUGIN_ROOT/scripts/review-gate.sh"

  export TEST_TMP PLUGIN_ROOT PROJECT_ROOT PHASE2_ENTRYPOINT REVIEW_GATE
}

teardown() {
  common_teardown
}

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------

# make_plan_file PLAN_PATH STORY_KEY PLAN_ID VERDICT VERDICT_PLAN_ID [SOURCES_JSON] [TESTS_JSON]
make_plan_file() {
  local plan_path="$1"
  local story_key="$2"
  local plan_id="$3"
  local verdict="$4"
  local verdict_plan_id="$5"
  local sources_json="${6:-[]}"
  local tests_json="${7:-[]}"

  mkdir -p "$(dirname "$plan_path")"
  cat > "$plan_path" <<YAML
---
template: test-automate-plan
story_key: "${story_key}"
plan_id: "${plan_id}"
phase: approved
approval:
  verdict: "${verdict}"
  verdict_plan_id: "${verdict_plan_id}"
analyzed_sources: ${sources_json}
proposed_tests: ${tests_json}
---

# Test Automate Plan: ${story_key}

Generated by Phase 1.
YAML
}

# make_test_env YAML_PATH ALLOWLIST_DIR
make_test_env() {
  local yaml_path="$1"
  local allowlist_dir="$2"

  mkdir -p "$(dirname "$yaml_path")"
  cat > "$yaml_path" <<YAML
---
tier_directories:
  - "${allowlist_dir}"
YAML
}

# seed_ledger LEDGER_PATH STORY_KEY PLAN_ID [VERDICT]
# Tab-separated: story_key <TAB> gate-name <TAB> plan_id <TAB> verdict
seed_ledger() {
  local ledger_path="$1"
  local story_key="$2"
  local plan_id="$3"
  local verdict="${4:-PASSED}"

  mkdir -p "$(dirname "$ledger_path")"
  printf '%s\t%s\t%s\t%s\n' \
    "$story_key" "test-automate-plan" "$plan_id" "$verdict" \
    >> "$ledger_path"
}

# sha256_of FILE — portable SHA-256 hex digest
sha256_of() {
  if command -v shasum &>/dev/null; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

# seed_story_artifact PATH STORY_KEY — minimal implementation artifact with Review Gate table
seed_story_artifact() {
  local path="$1"
  local story_key="$2"

  mkdir -p "$(dirname "$path")"
  cat > "$path" <<STORY
---
template: 'story'
key: "${story_key}"
status: review
---

# Story: ${story_key}

## Review Gate

| Review | Status | Report |
|--------|--------|--------|
| Code Review | PASSED | — |
| QA Tests | PASSED | — |
| Security Review | PASSED | — |
| Test Automation | UNVERIFIED | — |
| Test Review | PASSED | — |
| Performance Review | PASSED | — |
STORY
}

# ---------------------------------------------------------------------------
# AC1 — Triple-source verdict all agree → Phase 2 proceeds to Step 1
# [TC-TAF-7, FR-TAF-4]
# ---------------------------------------------------------------------------

@test "AC1: happy_path_triple_source_verdict_all_agree_phase2_proceeds" {
  local story_key="E35-S3-AC1"
  local plan_id="plan-$(date +%s)-ac1"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests"

  mkdir -p "$allowlist_dir"
  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" "[]" "[]"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  # All three sources agree; Phase 2 must proceed past Step 0 without HALT.
  [ "$status" -eq 0 ]
  [[ "$output" != *"plan_id_mismatch"* ]]
  [[ "$output" != *"HALT"* ]]
  [[ "$output" == *"Step 0: verdict sources agree"* ]] || \
    [[ "$output" == *"verdict_sources_ok"* ]]
}

# ---------------------------------------------------------------------------
# AC2 — plan_id mismatch (concurrent-execution race) → HALT plan_id_mismatch
# [TC-TAF-6, FR-TAF-4]
# ---------------------------------------------------------------------------

@test "AC2: halt_on_plan_id_mismatch_concurrent_race" {
  local story_key="E35-S3-AC2"
  local plan_id_disk="plan-disk-$(date +%s)"
  local plan_id_ledger="plan-ledger-$(date +%s)-different"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests"

  mkdir -p "$allowlist_dir"
  make_plan_file "$plan_path" "$story_key" "$plan_id_disk" "PASSED" "$plan_id_disk" "[]" "[]"
  make_test_env "$test_env_path" "$allowlist_dir"
  # Ledger was written for a different plan execution.
  seed_ledger "$ledger_path" "$story_key" "$plan_id_ledger" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"plan_id_mismatch"* ]]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC3 — Plan-file frontmatter tampered (verdict_plan_id changed after approval)
#        → HALT plan_tamper_detected
# [TC-TAF-9, FR-TAF-4]
# ---------------------------------------------------------------------------

@test "AC3: halt_on_plan_tamper_frontmatter_verdict_plan_id_divergence" {
  local story_key="E35-S3-AC3"
  local plan_id="plan-$(date +%s)-ac3"
  local tampered_id="plan-tampered-$(date +%s)"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests"

  mkdir -p "$allowlist_dir"
  # plan_id matches ledger, but verdict_plan_id was tampered to a different value.
  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$tampered_id" "[]" "[]"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"plan_tamper_detected"* ]]
  [[ "$output" == *"frontmatter"* ]] || [[ "$output" == *"diverge"* ]]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC4 — Source file modified between Phase 1 and Phase 2 → HALT plan_drift
# [TC-TAF-4, FR-TAF-3]
# ---------------------------------------------------------------------------

@test "AC4: halt_on_source_drift_sha256_mismatch" {
  local story_key="E35-S3-AC4"
  local plan_id="plan-$(date +%s)-ac4"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests"
  local source_file="$TEST_TMP/src/target.sh"

  mkdir -p "$allowlist_dir" "$(dirname "$source_file")"
  printf '#!/usr/bin/env bash\necho hello\n' > "$source_file"
  local original_sha
  original_sha="$(sha256_of "$source_file")"

  local sources_json
  sources_json='[{"path":"'"$source_file"'","sha256":"'"$original_sha"'"}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "$sources_json" "[]"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  # Simulate drift: modify source AFTER plan was approved.
  printf '#!/usr/bin/env bash\necho world  # MODIFIED\n' > "$source_file"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"plan_drift"* ]]
  [[ "$output" == *"$source_file"* ]]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
  [ -z "$(find "$allowlist_dir" -type f 2>/dev/null | head -1)" ]
}

# ---------------------------------------------------------------------------
# AC5 — proposed_tests path outside tier-directory allowlist
#        → HALT target_path_out_of_scope
# [TC-TAF-5, FR-TAF-3]
# ---------------------------------------------------------------------------

@test "AC5: halt_on_proposed_test_path_outside_tier_allowlist" {
  local story_key="E35-S3-AC5"
  local plan_id="plan-$(date +%s)-ac5"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/allowed-tests"
  local outside_path="/tmp/outside-ac5-$$/evil.test.js"

  mkdir -p "$allowlist_dir"

  local tests_json='[{"test_file":"'"$outside_path"'","test_cases":[]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"target_path_out_of_scope"* ]]
  [[ "$output" == *"$outside_path"* ]]
  [ ! -f "$outside_path" ]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC6 — Minimal happy-path end-to-end: test file written + evidence produced
# [TC-TAF-7, FR-TAF-1, FR-TAF-3]
# ---------------------------------------------------------------------------

@test "AC6: happy_path_end_to_end_minimal_fixture_test_written_evidence_produced" {
  local story_key="E35-S3-AC6"
  local plan_id="plan-$(date +%s)-ac6"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/happy-path"
  local source_file="$TEST_TMP/src/widget.sh"
  local test_file="$allowlist_dir/widget.test.bats"
  local evidence_path="$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json"

  mkdir -p "$allowlist_dir" "$(dirname "$source_file")" "$(dirname "$evidence_path")"
  printf '#!/usr/bin/env bash\nwidget() { echo ok; }\n' > "$source_file"
  local sha
  sha="$(sha256_of "$source_file")"

  local sources_json='[{"path":"'"$source_file"'","sha256":"'"$sha"'"}]'
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"widget outputs ok","assertion":"widget output equals ok"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "$sources_json" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -eq 0 ]
  [ -f "$test_file" ]
  [ -f "$evidence_path" ]
  grep -q '"story_key"' "$evidence_path"
  grep -q '"PASSED"' "$evidence_path"
  local test_count
  test_count="$(grep -c '"name"' "$evidence_path" || true)"
  [ "$test_count" -ge 1 ]
}

# ---------------------------------------------------------------------------
# AC7 — Phase 2 operates in main context; Write and Edit succeed
# [FR-TAF-1]
# ---------------------------------------------------------------------------

@test "AC7: phase2_runs_in_main_context_write_and_edit_allowed" {
  local story_key="E35-S3-AC7"
  local plan_id="plan-$(date +%s)-ac7"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/main-ctx"
  local source_file="$TEST_TMP/src/ctx-widget.sh"
  local test_file="$allowlist_dir/ctx-widget.test.bats"

  mkdir -p "$allowlist_dir" "$(dirname "$source_file")"
  printf '#!/usr/bin/env bash\nctx_widget() { echo ctx-ok; }\n' > "$source_file"
  local sha
  sha="$(sha256_of "$source_file")"

  local sources_json='[{"path":"'"$source_file"'","sha256":"'"$sha"'"}]'
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"ctx-widget","assertion":"output equals ctx-ok"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "$sources_json" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  # A file written to disk proves main (non-fork) context access.
  [ "$status" -eq 0 ]
  [ -f "$test_file" ]
  [[ "$output" != *"context: fork"* ]]
  [[ "$output" != *"fork subagent"* ]]
}

# ---------------------------------------------------------------------------
# AC8 — Phase 2 complete → plan phase=executed + story Review Gate + sprint
# [FR-TAF-1]
# ---------------------------------------------------------------------------

@test "AC8: phase2_complete_plan_phase_executed_story_sprint_updated" {
  local story_key="E35-S3-AC8"
  local plan_id="plan-$(date +%s)-ac8"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/ac8"
  local source_file="$TEST_TMP/src/ac8-widget.sh"
  local test_file="$allowlist_dir/ac8-widget.test.bats"
  local story_artifact="$TEST_TMP/docs/implementation-artifacts/${story_key}-fake.md"

  mkdir -p "$allowlist_dir" "$(dirname "$source_file")"
  printf '#!/usr/bin/env bash\nac8() { echo ac8; }\n' > "$source_file"
  local sha
  sha="$(sha256_of "$source_file")"

  local sources_json='[{"path":"'"$source_file"'","sha256":"'"$sha"'"}]'
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"ac8 test","assertion":"output equals ac8"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "$sources_json" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"
  seed_story_artifact "$story_artifact" "$story_key"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -eq 0 ]

  # Plan file phase updated to "executed".
  grep -q 'phase: executed' "$plan_path" || grep -q '"phase":"executed"' "$plan_path"

  # Plan file contains execution_summary block.
  grep -qi 'execution_summary' "$plan_path"

  # Story Review Gate row for Test Automation updated to PASSED.
  grep -q 'Test Automation | PASSED' "$story_artifact"
}

# ---------------------------------------------------------------------------
# AC9 — V1 regression fixture → new test files written and executed
# [TC-TAF-7]
# ---------------------------------------------------------------------------

@test "AC9: v1_regression_fixture_test_files_written_and_executed" {
  local story_key="E35-S3-AC9"
  local plan_id="plan-v1-parity-$(date +%s)"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local fixture_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/v1-parity"
  local source_file="$fixture_dir/legacy-feature.sh"
  local test_file="$fixture_dir/legacy-feature.test.bats"
  local evidence_path="$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json"

  mkdir -p "$fixture_dir" "$(dirname "$evidence_path")"

  cat > "$source_file" <<'SHELL'
#!/usr/bin/env bash
# Legacy V1 feature — must be tested by Phase 2 regression suite.
legacy_compute() { echo "$(( $1 + $2 ))"; }
SHELL

  local sha
  sha="$(sha256_of "$source_file")"

  local sources_json='[{"path":"'"$source_file"'","sha256":"'"$sha"'"}]'
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"legacy_compute adds two numbers","assertion":"legacy_compute 3 4 equals 7"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "$sources_json" "$tests_json"
  make_test_env "$test_env_path" "$fixture_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -eq 0 ]
  [ -f "$test_file" ]
  [ -f "$evidence_path" ]
  grep -q '"executed"' "$evidence_path" || grep -q '"tests_run"' "$evidence_path"
}

# ---------------------------------------------------------------------------
# AC-EC1 — Empty analyzed_sources[] → drift check no-op; proceed to Step 2
# [boundary]
# ---------------------------------------------------------------------------

@test "AC-EC1: edge_empty_analyzed_sources_drift_check_noop" {
  local story_key="E35-S3-EC1"
  local plan_id="plan-$(date +%s)-ec1"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/ec1"
  local test_file="$allowlist_dir/ec1.test.bats"

  mkdir -p "$allowlist_dir"
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"ec1 smoke","assertion":"true"}]}]'

  # analyzed_sources is intentionally empty.
  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -eq 0 ]
  [[ "$output" != *"plan_drift"* ]]
  [ -f "$test_file" ]
}

# ---------------------------------------------------------------------------
# AC-EC2 — Empty proposed_tests[] → zero files written; evidence 0 cases
# [boundary]
# ---------------------------------------------------------------------------

@test "AC-EC2: edge_empty_proposed_tests_zero_files_written" {
  local story_key="E35-S3-EC2"
  local plan_id="plan-$(date +%s)-ec2"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/ec2"
  local evidence_path="$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json"

  mkdir -p "$allowlist_dir" "$(dirname "$evidence_path")"

  # proposed_tests is intentionally empty.
  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "[]"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -eq 0 ]
  local file_count
  file_count="$(find "$allowlist_dir" -type f 2>/dev/null | wc -l | tr -d ' ')"
  [ "$file_count" -eq 0 ]
  [ -f "$evidence_path" ]
  grep -q '"tests_run":0' "$evidence_path" || \
    grep -q '"test_count":0' "$evidence_path" || \
    grep -q '"cases":\[\]' "$evidence_path"
}

# ---------------------------------------------------------------------------
# AC-EC3 — Plan file missing → HALT "plan file not found at {path}"; no writes
# [error]
# ---------------------------------------------------------------------------

@test "AC-EC3: edge_plan_file_missing_halt_not_found" {
  local story_key="E35-S3-EC3"
  local plan_path="$TEST_TMP/does-not-exist/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/allowed"

  mkdir -p "$allowlist_dir"
  make_test_env "$test_env_path" "$allowlist_dir"
  # Plan file deliberately not created.

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"plan file not found"* ]] || [[ "$output" == *"not found"* ]]
  [[ "$output" == *"$plan_path"* ]]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC-EC4 — Malformed YAML frontmatter → HALT plan_tamper_detected; no writes
# [data]
# ---------------------------------------------------------------------------

@test "AC-EC4: edge_malformed_yaml_frontmatter_halt_plan_tamper_detected" {
  local story_key="E35-S3-EC4"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/allowed"
  local plan_id="plan-$(date +%s)-ec4"

  mkdir -p "$allowlist_dir" "$(dirname "$plan_path")"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  # Write intentionally broken YAML frontmatter.
  cat > "$plan_path" <<'BROKEN'
---
template: test-automate-plan
plan_id: "unclosed-string
approval:
  verdict: PASSED
  verdict_plan_id: [invalid: yaml: here
analyzed_sources: NOT_AN_ARRAY
---

# Broken plan
BROKEN

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"plan_tamper_detected"* ]]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC-EC5 — Path traversal in proposed_tests[].test_file → HALT out_of_scope
# [security]
# ---------------------------------------------------------------------------

@test "AC-EC5: edge_path_traversal_in_proposed_test_file_halts" {
  local story_key="E35-S3-EC5"
  local plan_id="plan-$(date +%s)-ec5"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests"

  mkdir -p "$allowlist_dir"

  # Path uses ../ traversal to escape the allowlist boundary.
  local traversal_path="$allowlist_dir/../../../etc/passwd.test.js"

  local tests_json='[{"test_file":"'"$traversal_path"'","test_cases":[]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"target_path_out_of_scope"* ]]
  # The resolved canonical path of the traversal target must not have been written.
  [ ! -f "/etc/passwd.test.js" ]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC-EC6 — test-environment.yaml missing → HALT; no fallback allowlist
# [environment]
# ---------------------------------------------------------------------------

@test "AC-EC6: edge_test_environment_yaml_missing_halt_no_fallback" {
  local story_key="E35-S3-EC6"
  local plan_id="plan-$(date +%s)-ec6"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  # Point at a test-environment.yaml that does NOT exist.
  local test_env_path="$TEST_TMP/does-not-exist/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/tests"

  mkdir -p "$allowlist_dir"
  local test_file="$allowlist_dir/ec6.test.bats"
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"ec6","assertion":"true"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "$tests_json"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"
  # Deliberately do NOT create test-environment.yaml.

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"test-environment"* ]] || [[ "$output" == *"missing"* ]]
  [ ! -f "$test_file" ]
}

# ---------------------------------------------------------------------------
# AC-EC7 — Source modified DURING Phase 2 (documented limitation — skipped)
# [concurrency — documented, not coded]
# ---------------------------------------------------------------------------

# @todo FR-TAF-CONCURRENCY: Documented known limitation.
# Phase 2 drift-checks at Step 1 and invokes the Bridge at Step 4.
# A source file modified between these two steps is undetected.
# The Bridge executes against the modified filesystem.
# When a mid-phase detection mechanism is added, update this test to assert
# HALT status: mid_phase_drift.
@test "AC-EC7: edge_source_modified_during_phase2_documented_limitation" {
  skip "Known limitation: concurrent modification between drift-check (Step 1) and Bridge invocation (Step 4) is not detected. Bridge executes against current filesystem. See ADR-028 known limitations and FR-TAF-CONCURRENCY."
}

# ---------------------------------------------------------------------------
# AC-EC8 — Bridge unavailable → test files written; bridge-failure annotation;
#           plan phase=executed
# [integration]
# ---------------------------------------------------------------------------

@test "AC-EC8: edge_bridge_unavailable_files_written_annotation_added" {
  local story_key="E35-S3-EC8"
  local plan_id="plan-$(date +%s)-ec8"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/ec8"
  local source_file="$TEST_TMP/src/ec8-widget.sh"
  local test_file="$allowlist_dir/ec8-widget.test.bats"
  local evidence_path="$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json"

  mkdir -p "$allowlist_dir" "$(dirname "$source_file")" "$(dirname "$evidence_path")"
  printf '#!/usr/bin/env bash\nec8_widget() { echo ec8; }\n' > "$source_file"
  local sha
  sha="$(sha256_of "$source_file")"

  local sources_json='[{"path":"'"$source_file"'","sha256":"'"$sha"'"}]'
  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"ec8 test","assertion":"output equals ec8"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "$sources_json" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  # Stub PATH: only a minimal stub dir with no bridge binary.
  local stub_bin_dir="$TEST_TMP/stub-bin"
  mkdir -p "$stub_bin_dir"

  run env PATH="$stub_bin_dir" "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  # Test file must still be written despite bridge failure.
  [ -f "$test_file" ]

  # Evidence file produced with bridge_failure annotation.
  [ -f "$evidence_path" ]
  grep -qi 'bridge.failure\|bridge_failure\|bridge_unavailable' "$evidence_path"

  # Plan phase still set to executed.
  grep -q 'phase: executed' "$plan_path" || grep -q '"phase":"executed"' "$plan_path"
}

# ---------------------------------------------------------------------------
# AC-EC9 — Ledger empty or missing for gate tuple → HALT at Step 0
#           status: plan_id_mismatch
# [integration]
# ---------------------------------------------------------------------------

@test "AC-EC9: edge_ledger_empty_missing_halt_at_step0" {
  local story_key="E35-S3-EC9"
  local plan_id="plan-$(date +%s)-ec9"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  # Point at a ledger file that does NOT exist.
  local ledger_path="$TEST_TMP/does-not-exist-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/allowed"

  mkdir -p "$allowlist_dir"
  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "[]"
  make_test_env "$test_env_path" "$allowlist_dir"
  # Deliberately do NOT create ledger file.

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"plan_id_mismatch"* ]]
  [ ! -f "$TEST_TMP/docs/test-artifacts/test-results/${story_key}-execution.json" ]
}

# ---------------------------------------------------------------------------
# AC-EC10 — Target test file already exists → HALT to prevent clobbering
# [error]
# ---------------------------------------------------------------------------

@test "AC-EC10: edge_target_test_file_already_exists_halt" {
  local story_key="E35-S3-EC10"
  local plan_id="plan-$(date +%s)-ec10"
  local plan_path="$TEST_TMP/docs/test-artifacts/plans/${story_key}-plan.md"
  local ledger_path="$TEST_TMP/.review-gate-ledger"
  local test_env_path="$TEST_TMP/test-environment.yaml"
  local allowlist_dir="$TEST_TMP/gaia-public/plugins/gaia/tests/fixtures/test-automate-phase2/ec10"
  local test_file="$allowlist_dir/existing.test.bats"

  mkdir -p "$allowlist_dir"
  # Pre-create the test file — user work that must not be clobbered.
  printf '#!/usr/bin/env bats\n@test "pre-existing user test" { true; }\n' > "$test_file"

  local tests_json='[{"test_file":"'"$test_file"'","test_cases":[{"name":"new test","assertion":"true"}]}]'

  make_plan_file "$plan_path" "$story_key" "$plan_id" "PASSED" "$plan_id" \
    "[]" "$tests_json"
  make_test_env "$test_env_path" "$allowlist_dir"
  seed_ledger "$ledger_path" "$story_key" "$plan_id" "PASSED"

  local original_content
  original_content="$(cat "$test_file")"

  run "$PHASE2_ENTRYPOINT" \
    --story "$story_key" \
    --plan "$plan_path" \
    --ledger "$ledger_path" \
    --test-env "$test_env_path" \
    --project-root "$TEST_TMP"

  [ "$status" -ne 0 ]
  [[ "$output" == *"already exists"* ]] || [[ "$output" == *"clobber"* ]]

  # Original file content must be preserved — no clobbering occurred.
  local current_content
  current_content="$(cat "$test_file")"
  [ "$current_content" = "$original_content" ]
}
